Add Book object and modify JSON property
AY2223S2-CS2103T-T12-3/tp pull request #47
Opened 2023-03-09 05:00 UTC by glyfy

2023-03-09 12:54 UTC, Jarrett0203 requested changes
Additionally please try and fix the other compilation errors.

2023-03-09 12:54 UTC, Jarrett0203 commented on src/test/java/expresslibrary/testutil/PersonBuilder.java
>          return new Person(name, phone, email, address, tags);
```suggestion
        return new Person(name, phone, email, address, book, tags);
```

2023-03-12 11:52 UTC, kenzantonius approved these changes
LGTM

2023-03-12 14:47 UTC, Jarrett0203 approved these changes
LGTM

2023-03-12 15:09 UTC, kenzantonius approved these changes
LGTM

2023-03-12 15:09 UTC, merged